// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { services } from "npm:@/data/services";
var list_services_default = defineTool({
  name: "list_services",
  title: "List cleaning services",
  description: "List every cleaning service Capital Clean Care offers, with slug and a short description.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const items = services.map((s) => ({
      slug: s.slug,
      name: s.name,
      description: s.shortDescription
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { services: items }
    };
  }
});

// src/lib/mcp/tools/get-service.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
import { services as services2 } from "npm:@/data/services";
var get_service_default = defineTool2({
  name: "get_service",
  title: "Get service details",
  description: "Get full details for one cleaning service: intro, what's included, benefits and FAQs. Use list_services for valid slugs.",
  inputSchema: {
    slug: z.string().describe("Service slug, e.g. 'deep-cleaning'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ slug }) => {
    const service = services2.find((s) => s.slug === slug);
    if (!service) {
      throw new ToolError(
        `Unknown service '${slug}'. Valid slugs: ${services2.map((s) => s.slug).join(", ")}`
      );
    }
    const detail = {
      slug: service.slug,
      name: service.name,
      description: service.shortDescription,
      intro: service.intro,
      whatsIncluded: service.whatsIncluded,
      benefits: service.benefits,
      faqs: service.faqs
    };
    return {
      content: [{ type: "text", text: JSON.stringify(detail, null, 2) }],
      structuredContent: detail
    };
  }
});

// src/lib/mcp/tools/list-service-areas.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
import { cities } from "npm:@/data/locations";
var list_service_areas_default = defineTool3({
  name: "list_service_areas",
  title: "List service areas",
  description: "List the cities and counties Capital Clean Care serves across Maryland, Washington DC and Northern Virginia. Optionally filter by state abbreviation or a name search.",
  inputSchema: {
    state: z2.string().optional().describe("Filter by state abbreviation, e.g. MD, DC, VA."),
    search: z2.string().optional().describe("Case-insensitive substring match on the city name.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ state, search }) => {
    const stateFilter = state?.trim().toUpperCase();
    const searchFilter = search?.trim().toLowerCase();
    const items = cities.filter((c) => stateFilter ? c.state.toUpperCase() === stateFilter : true).filter((c) => searchFilter ? c.name.toLowerCase().includes(searchFilter) : true).map((c) => ({ name: c.name, slug: c.slug, state: c.state, county: c.county ?? null }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, areas: items }
    };
  }
});

// src/lib/mcp/tools/get-business-info.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { BUSINESS_INFO } from "npm:@/data/business-info";
var get_business_info_default = defineTool4({
  name: "get_business_info",
  title: "Get business info",
  description: "Get Capital Clean Care's public contact details, address, business hours, rating and differentiators.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: BUSINESS_INFO.name,
      phone: BUSINESS_INFO.phone.display,
      email: BUSINESS_INFO.email,
      website: BUSINESS_INFO.url,
      address: BUSINESS_INFO.address,
      hours: BUSINESS_INFO.hours,
      rating: BUSINESS_INFO.rating,
      differentiators: BUSINESS_INFO.differentiators
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/request-quote.ts
import { defineTool as defineTool5, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseAnon() {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/request-quote.ts
var request_quote_default = defineTool5({
  name: "request_quote",
  title: "Request a free cleaning quote",
  description: "Submit a free cleaning quote request to Capital Clean Care. Only submit with the customer's explicit confirmation of their real contact details.",
  inputSchema: {
    name: z3.string().describe("Customer full name."),
    phone: z3.string().describe("Customer phone number."),
    email: z3.string().describe("Customer email address."),
    zip: z3.string().describe("Service address zip code."),
    service: z3.string().describe("Requested service, e.g. 'deep-cleaning'."),
    bedrooms: z3.string().optional().describe("Number of bedrooms."),
    bathrooms: z3.string().optional().describe("Number of bathrooms."),
    frequency: z3.string().optional().describe("one-time, weekly, bi-weekly or monthly."),
    preferredDate: z3.string().optional().describe("Preferred date, YYYY-MM-DD."),
    message: z3.string().optional().describe("Any extra notes from the customer.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = supabaseAnon();
    const { error } = await supabase.from("quote_requests").insert({
      name: input.name,
      phone: input.phone,
      email: input.email,
      zip: input.zip,
      service: input.service,
      bedrooms: input.bedrooms ?? null,
      bathrooms: input.bathrooms ?? null,
      frequency: input.frequency ?? null,
      preferred_date: input.preferredDate ?? null,
      message: input.message ?? null
    });
    if (error) throw new ToolError2(`Could not submit the quote request: ${error.message}`);
    return {
      content: [
        {
          type: "text",
          text: `Quote request submitted for ${input.name}. The team will reach out by phone or email shortly.`
        }
      ],
      structuredContent: { submitted: true }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "capital-clean-launch",
  title: "Capital Clean Launch",
  version: "0.1.0",
  instructions: "Tools for Capital Clean Care, an eco-friendly house cleaning company serving Maryland, Washington DC and Northern Virginia. Use `list_services` and `get_service` for service details, `list_service_areas` for coverage, `get_business_info` for contact details, and `request_quote` to submit a free quote request once the customer confirms their details.",
  tools: [list_services_default, get_service_default, list_service_areas_default, get_business_info_default, request_quote_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
